"""remove_created_by_fk_from_user

Revision ID: 064010508069
Revises: 99dceb02253b
Create Date: 2026-02-05 13:30:57.087663

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '064010508069'
down_revision = '99dceb02253b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('provider', schema='docucr')
    # op.drop_table('client_location', schema='docucr')
    op.drop_constraint(op.f('user_created_by_fkey'), 'user', schema='docucr', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('user_created_by_fkey'), 'user', 'user', ['created_by'], ['id'], source_schema='docucr', referent_schema='docucr')
    pass
    # ### end Alembic commands ###
