"""add_organisation_id_to_document_list_configs

Revision ID: 0bc66bb69507
Revises: fc25e7c3fd57
Create Date: 2026-02-13 14:26:42.495172

"""
from alembic import op
import sqlalchemy as sa


revision = '0bc66bb69507'
down_revision = 'fc25e7c3fd57'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_list_configs', sa.Column('organisation_id', sa.String(), nullable=True), schema='docucr')
    op.create_foreign_key(None, 'document_list_configs', 'organisation', ['organisation_id'], ['id'], source_schema='docucr', referent_schema='docucr')
    op.alter_column('document_list_configs', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='docucr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_list_configs', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='docucr')
    op.drop_constraint(None, 'document_list_configs', schema='docucr', type_='foreignkey')
    op.drop_column('document_list_configs', 'organisation_id', schema='docucr')
    # ### end Alembic commands ###
