"""Add client_id foreign key to documents table

Revision ID: 129948718cb2
Revises: 51766ed697b6
Create Date: 2026-01-29 11:18:57.193711

"""
from alembic import op
import sqlalchemy as sa


revision = '129948718cb2'
down_revision = '51766ed697b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'state_code',
               existing_type=sa.CHAR(length=2),
               type_=sa.String(length=2),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('client', 'country',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True,
               schema='docucr')
    op.alter_column('client', 'zip_code',
               existing_type=sa.CHAR(length=5),
               type_=sa.String(length=5),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('client', 'zip_extension',
               existing_type=sa.CHAR(length=4),
               type_=sa.String(length=4),
               existing_nullable=True,
               schema='docucr')
    op.add_column('documents', sa.Column('client_id', sa.UUID(), nullable=True), schema='docucr')
    op.alter_column('documents', 'enable_ai',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False,
               schema='docucr')
    op.create_foreign_key(None, 'documents', 'client', ['client_id'], ['id'], source_schema='docucr', referent_schema='docucr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', schema='docucr', type_='foreignkey')
    op.alter_column('documents', 'enable_ai',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False,
               schema='docucr')
    op.drop_column('documents', 'client_id', schema='docucr')
    op.alter_column('client', 'zip_extension',
               existing_type=sa.String(length=4),
               type_=sa.CHAR(length=4),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('client', 'zip_code',
               existing_type=sa.String(length=5),
               type_=sa.CHAR(length=5),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('client', 'country',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'United States'::character varying"),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('client', 'state_code',
               existing_type=sa.String(length=2),
               type_=sa.CHAR(length=2),
               existing_nullable=True,
               schema='docucr')
    # ### end Alembic commands ###
