"""create_organisation_role_table

Revision ID: 1bb1b7add63a
Revises: e24b3143f299
Create Date: 2026-02-04 23:43:09.948138

"""
from alembic import op
import sqlalchemy as sa


revision = '1bb1b7add63a'
down_revision = 'e24b3143f299'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisation_role',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['docucr.organisation.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['docucr.role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='docucr'
    )
    op.create_index(op.f('ix_docucr_organisation_role_id'), 'organisation_role', ['id'], unique=False, schema='docucr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_docucr_organisation_role_id'), table_name='organisation_role', schema='docucr')
    op.drop_table('organisation_role', schema='docucr')
    # ### end Alembic commands ###
