"""baseline

Revision ID: 1d7e80a3d5e0
Revises: 
Create Date: 2026-02-20 12:57:21.353715

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '1d7e80a3d5e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('npi', sa.String(length=10), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('address_line_1', sa.String(length=250), nullable=True),
    sa.Column('address_line_2', sa.String(length=250), nullable=True),
    sa.Column('city', sa.String(length=250), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('state_name', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('is_user', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('organisation_id', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("zip_code ~ '^[0-9]{5}-[0-9]{4}$'", name='ck_client_zip_9_digit'),
    sa.CheckConstraint('char_length(state_code) = 2', name='ck_client_state_code_len'),
    sa.ForeignKeyConstraint(['created_by'], ['docucr.user.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['docucr.organisation.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['docucr.status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='docucr'
    )
    op.create_index(op.f('ix_docucr_client_id'), 'client', ['id'], unique=False, schema='docucr')
    op.create_index(op.f('ix_docucr_client_npi'), 'client', ['npi'], unique=False, schema='docucr')
    op.create_table('module',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('route', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('has_submodules', sa.Boolean(), nullable=True),
    sa.Column('submodules', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('color_from', sa.String(), nullable=True),
    sa.Column('color_to', sa.String(), nullable=True),
    sa.Column('color_shadow', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='docucr'
    )
    op.create_index(op.f('ix_docucr_module_id'), 'module', ['id'], unique=False, schema='docucr')
    op.create_index(op.f('ix_docucr_module_name'), 'module', ['name'], unique=True, schema='docucr')
    op.create_table('otp',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('otp_code', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='docucr'
    )
    op.create_index(op.f('ix_docucr_otp_email'), 'otp', ['email'], unique=False, schema='docucr')
    op.create_index(op.f('ix_docucr_otp_id'), 'otp', ['id'], unique=False, schema='docucr')
    op.create_table('printer',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='docucr'
    )
    op.create_index(op.f('ix_docucr_printer_id'), 'printer', ['id'], unique=False, schema='docucr')
    op.create_table('privilege',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='docucr'
    )
    op.create_index(op.f('ix_docucr_privilege_id'), 'privilege', ['id'], unique=False, schema='docucr')
    op.create_index(op.f('ix_docucr_privilege_name'), 'privilege', ['name'], unique=True, schema='docucr')
    op.create_table('provider',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('npi', sa.String(), nullable=True),
    sa.Column('address_line_1', sa.String(length=250), nullable=True),
    sa.Column('address_line_2', sa.String(length=250), nullable=True),
    sa.Column('city', sa.String(length=250), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('state_name', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("zip_code ~ '^[0-9]{5}-[0-9]{4}$'", name='ck_client_zip_9_digit'),
    sa.CheckConstraint('char_length(state_code) = 2', name='ck_client_state_code_len'),
    sa.PrimaryKeyConstraint('id'),
    schema='docucr'
    )
    op.create_index(op.f('ix_docucr_provider_npi'), 'provider', ['npi'], unique=True, schema='docucr')
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='docucr'
    )
    op.create_index(op.f('ix_docucr_status_code'), 'status', ['code'], unique=True, schema='docucr')
    op.create_index(op.f('ix_docucr_status_id'), 'status', ['id'], unique=False, schema='docucr')
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('phone_country_code', sa.String(length=5), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_supervisor', sa.Boolean(), nullable=True),
    sa.Column('is_client', sa.Boolean(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('organisation_id', sa.String(), nullable=True),
    sa.Column('profile_image_url', sa.String(), nullable=True),
    # sa.ForeignKeyConstraint(['client_id'], ['docucr.client.id'], ),
    # sa.ForeignKeyConstraint(['created_by'], ['docucr.user.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['docucr.organisation.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['docucr.status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='docucr'
    )
    op.create_index(op.f('ix_docucr_user_email'), 'user', ['email'], unique=True, schema='docucr')
    op.create_index(op.f('ix_docucr_user_id'), 'user', ['id'], unique=False, schema='docucr')
    op.create_index(op.f('ix_docucr_user_username'), 'user', ['username'], unique=True, schema='docucr')
    op.create_table('client_location',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('address_line_1', sa.String(), nullable=False),
    sa.Column('address_line_2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state_code', sa.String(), nullable=False),
    sa.Column('state_name', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    # sa.ForeignKeyConstraint(['client_id'], ['docucr.client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='docucr'
    )
    op.create_table('organisation',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['docucr.status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='docucr'
    )
    op.create_table('submodule',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('module_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('route_key', sa.String(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['docucr.module.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='docucr'
    )
    op.create_index(op.f('ix_docucr_submodule_id'), 'submodule', ['id'], unique=False, schema='docucr')
    op.create_table('user_supervisor',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('supervisor_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['supervisor_id'], ['docucr.user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['docucr.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='docucr'
    )
    op.create_index(op.f('ix_docucr_user_supervisor_id'), 'user_supervisor', ['id'], unique=False, schema='docucr')
    op.create_table('webhook',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=True),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['docucr.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='docucr'
    )
    op.create_index(op.f('ix_docucr_webhook_id'), 'webhook', ['id'], unique=False, schema='docucr')
    op.create_table('activity_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('organisation_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['docucr.organisation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['docucr.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='docucr'
    )
    op.create_table('document_list_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('organisation_id', sa.String(), nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['docucr.organisation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['docucr.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='docucr'
    )
    op.create_index(op.f('ix_docucr_document_list_configs_id'), 'document_list_configs', ['id'], unique=False, schema='docucr')
    op.create_table('document_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['docucr.organisation.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['docucr.status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='docucr'
    )
    op.create_table('form',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organisation_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['docucr.organisation.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['docucr.status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='docucr'
    )
    op.create_index(op.f('ix_docucr_form_id'), 'form', ['id'], unique=False, schema='docucr')
    op.create_index(op.f('ix_docucr_form_name'), 'form', ['name'], unique=False, schema='docucr')
    op.create_table('role',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('can_edit', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('organisation_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['docucr.user.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['docucr.organisation.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['docucr.status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'organisation_id', name='ux_role_name_org'),
    schema='docucr'
    )
    op.create_index(op.f('ix_docucr_role_id'), 'role', ['id'], unique=False, schema='docucr')
    op.create_index(op.f('ix_docucr_role_name'), 'role', ['name'], unique=False, schema='docucr')
    op.create_table('sop',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('provider_type', sa.String(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('provider_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('workflow_process', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('billing_guidelines', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payer_guidelines', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('coding_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('coding_rules_cpt', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('coding_rules_icd', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('workflow_status_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('organisation_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['docucr.client.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['docucr.user.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['docucr.organisation.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['docucr.status.id'], ),
    sa.ForeignKeyConstraint(['workflow_status_id'], ['docucr.status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='docucr'
    )
    op.create_index(op.f('ix_docucr_sop_id'), 'sop', ['id'], unique=False, schema='docucr')
    op.create_table('user_client',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.String(), nullable=True),
    sa.Column('organisation_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['docucr.user.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['docucr.client.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['docucr.organisation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['docucr.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_id', name='uq_user_client'),
    schema='docucr'
    )
    op.create_index(op.f('ix_docucr_user_client_id'), 'user_client', ['id'], unique=False, schema='docucr')
    op.create_table('form_field',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('form_id', sa.String(), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('placeholder', sa.String(length=200), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('default_value', sa.JSON(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('validation', sa.JSON(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['docucr.form.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='docucr'
    )
    op.create_index(op.f('ix_docucr_form_field_id'), 'form_field', ['id'], unique=False, schema='docucr')
    op.create_table('role_module',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('module_id', sa.String(), nullable=False),
    sa.Column('privilege_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['docucr.module.id'], ),
    sa.ForeignKeyConstraint(['privilege_id'], ['docucr.privilege.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['docucr.role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='docucr'
    )
    op.create_index(op.f('ix_docucr_role_module_id'), 'role_module', ['id'], unique=False, schema='docucr')
    op.create_table('role_submodule',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('submodule_id', sa.String(), nullable=False),
    sa.Column('privilege_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['privilege_id'], ['docucr.privilege.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['docucr.role.id'], ),
    sa.ForeignKeyConstraint(['submodule_id'], ['docucr.submodule.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='docucr'
    )
    op.create_index(op.f('ix_docucr_role_submodule_id'), 'role_submodule', ['id'], unique=False, schema='docucr')
    op.create_table('sop_provider_mapping',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sop_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['docucr.provider.id'], ),
    sa.ForeignKeyConstraint(['sop_id'], ['docucr.sop.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='docucr'
    )
    op.create_table('templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('document_type_id', sa.UUID(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('extraction_fields', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('organisation_id', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['docucr.user.id'], ),
    sa.ForeignKeyConstraint(['document_type_id'], ['docucr.document_types.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['docucr.organisation.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['docucr.status.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['docucr.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_name', 'document_type_id'),
    schema='docucr'
    )
    op.create_table('user_role',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organisation_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['docucr.organisation.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['docucr.role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['docucr.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='docucr'
    )
    op.create_index(op.f('ix_docucr_user_role_id'), 'user_role', ['id'], unique=False, schema='docucr')
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=True),
    sa.Column('s3_bucket', sa.String(length=100), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('upload_progress', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('analysis_report_s3_key', sa.String(length=500), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('document_type_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('enable_ai', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['docucr.client.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['docucr.user.id'], ),
    sa.ForeignKeyConstraint(['document_type_id'], ['docucr.document_types.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['docucr.organisation.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['docucr.status.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['docucr.templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='docucr'
    )
    op.create_index(op.f('ix_docucr_documents_id'), 'documents', ['id'], unique=False, schema='docucr')
    op.create_table('user_role_module',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role_module_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_module_id'], ['docucr.role_module.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['docucr.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='docucr'
    )
    op.create_index(op.f('ix_docucr_user_role_module_id'), 'user_role_module', ['id'], unique=False, schema='docucr')
    op.create_table('document_form_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['docucr.documents.id'], ),
    sa.ForeignKeyConstraint(['form_id'], ['docucr.form.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id'),
    schema='docucr'
    )
    op.create_index(op.f('ix_docucr_document_form_data_id'), 'document_form_data', ['id'], unique=False, schema='docucr')
    op.create_table('document_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('shared_by_user_id', sa.String(), nullable=True),
    sa.Column('shared_by_org_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['docucr.documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_by_org_id'], ['docucr.organisation.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shared_by_user_id'], ['docucr.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['docucr.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'user_id', name='uq_document_user_share'),
    schema='docucr'
    )
    op.create_index('ix_document_shares_document_id', 'document_shares', ['document_id'], unique=False, schema='docucr')
    op.create_index('ix_document_shares_user_id', 'document_shares', ['user_id'], unique=False, schema='docucr')
    op.create_table('external_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('shared_by_user_id', sa.String(), nullable=True),
    sa.Column('shared_by_org_id', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['docucr.documents.id'], ),
    sa.ForeignKeyConstraint(['shared_by_org_id'], ['docucr.organisation.id'], ),
    sa.ForeignKeyConstraint(['shared_by_user_id'], ['docucr.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='docucr'
    )
    op.create_index(op.f('ix_docucr_external_shares_token'), 'external_shares', ['token'], unique=True, schema='docucr')
    op.create_table('extracted_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('document_type_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('page_range', sa.String(length=50), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['docucr.documents.id'], ),
    sa.ForeignKeyConstraint(['document_type_id'], ['docucr.document_types.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['docucr.templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='docucr'
    )
    op.create_table('unverified_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('suspected_type', sa.String(length=100), nullable=True),
    sa.Column('page_range', sa.String(length=50), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['docucr.documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='docucr'
    )
    op.create_foreign_key(
    "fk_client_created_by",
    "client", "user",
    ["created_by"], ["id"],
    source_schema="docucr",
    referent_schema="docucr"
    )

    op.create_foreign_key(
        "fk_user_client_id",
        "user", "client",
        ["client_id"], ["id"],
        source_schema="docucr",
        referent_schema="docucr"
    )

    op.create_foreign_key(
        "fk_user_created_by",
        "user", "user",
        ["created_by"], ["id"],
        source_schema="docucr",
        referent_schema="docucr"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unverified_documents', schema='docucr')
    op.drop_table('extracted_documents', schema='docucr')
    op.drop_index(op.f('ix_docucr_external_shares_token'), table_name='external_shares', schema='docucr')
    op.drop_table('external_shares', schema='docucr')
    op.drop_index('ix_document_shares_user_id', table_name='document_shares', schema='docucr')
    op.drop_index('ix_document_shares_document_id', table_name='document_shares', schema='docucr')
    op.drop_table('document_shares', schema='docucr')
    op.drop_index(op.f('ix_docucr_document_form_data_id'), table_name='document_form_data', schema='docucr')
    op.drop_table('document_form_data', schema='docucr')
    op.drop_index(op.f('ix_docucr_user_role_module_id'), table_name='user_role_module', schema='docucr')
    op.drop_table('user_role_module', schema='docucr')
    op.drop_index(op.f('ix_docucr_documents_id'), table_name='documents', schema='docucr')
    op.drop_table('documents', schema='docucr')
    op.drop_index(op.f('ix_docucr_user_role_id'), table_name='user_role', schema='docucr')
    op.drop_table('user_role', schema='docucr')
    op.drop_table('templates', schema='docucr')
    op.drop_table('sop_provider_mapping', schema='docucr')
    op.drop_index(op.f('ix_docucr_role_submodule_id'), table_name='role_submodule', schema='docucr')
    op.drop_table('role_submodule', schema='docucr')
    op.drop_index(op.f('ix_docucr_role_module_id'), table_name='role_module', schema='docucr')
    op.drop_table('role_module', schema='docucr')
    op.drop_index(op.f('ix_docucr_form_field_id'), table_name='form_field', schema='docucr')
    op.drop_table('form_field', schema='docucr')
    op.drop_index(op.f('ix_docucr_user_client_id'), table_name='user_client', schema='docucr')
    op.drop_table('user_client', schema='docucr')
    op.drop_index(op.f('ix_docucr_sop_id'), table_name='sop', schema='docucr')
    op.drop_table('sop', schema='docucr')
    op.drop_index(op.f('ix_docucr_role_name'), table_name='role', schema='docucr')
    op.drop_index(op.f('ix_docucr_role_id'), table_name='role', schema='docucr')
    op.drop_table('role', schema='docucr')
    op.drop_index(op.f('ix_docucr_form_name'), table_name='form', schema='docucr')
    op.drop_index(op.f('ix_docucr_form_id'), table_name='form', schema='docucr')
    op.drop_table('form', schema='docucr')
    op.drop_table('document_types', schema='docucr')
    op.drop_index(op.f('ix_docucr_document_list_configs_id'), table_name='document_list_configs', schema='docucr')
    op.drop_table('document_list_configs', schema='docucr')
    op.drop_table('activity_log', schema='docucr')
    op.drop_index(op.f('ix_docucr_webhook_id'), table_name='webhook', schema='docucr')
    op.drop_table('webhook', schema='docucr')
    op.drop_index(op.f('ix_docucr_user_supervisor_id'), table_name='user_supervisor', schema='docucr')
    op.drop_table('user_supervisor', schema='docucr')
    op.drop_index(op.f('ix_docucr_submodule_id'), table_name='submodule', schema='docucr')
    op.drop_table('submodule', schema='docucr')
    op.drop_table('organisation', schema='docucr')
    op.drop_table('client_location', schema='docucr')
    op.drop_index(op.f('ix_docucr_user_username'), table_name='user', schema='docucr')
    op.drop_index(op.f('ix_docucr_user_id'), table_name='user', schema='docucr')
    op.drop_index(op.f('ix_docucr_user_email'), table_name='user', schema='docucr')
    op.drop_table('user', schema='docucr')
    op.drop_index(op.f('ix_docucr_status_id'), table_name='status', schema='docucr')
    op.drop_index(op.f('ix_docucr_status_code'), table_name='status', schema='docucr')
    op.drop_table('status', schema='docucr')
    op.drop_index(op.f('ix_docucr_provider_npi'), table_name='provider', schema='docucr')
    op.drop_table('provider', schema='docucr')
    op.drop_index(op.f('ix_docucr_privilege_name'), table_name='privilege', schema='docucr')
    op.drop_index(op.f('ix_docucr_privilege_id'), table_name='privilege', schema='docucr')
    op.drop_table('privilege', schema='docucr')
    op.drop_index(op.f('ix_docucr_printer_id'), table_name='printer', schema='docucr')
    op.drop_table('printer', schema='docucr')
    op.drop_index(op.f('ix_docucr_otp_id'), table_name='otp', schema='docucr')
    op.drop_index(op.f('ix_docucr_otp_email'), table_name='otp', schema='docucr')
    op.drop_table('otp', schema='docucr')
    op.drop_index(op.f('ix_docucr_module_name'), table_name='module', schema='docucr')
    op.drop_index(op.f('ix_docucr_module_id'), table_name='module', schema='docucr')
    op.drop_table('module', schema='docucr')
    op.drop_index(op.f('ix_docucr_client_npi'), table_name='client', schema='docucr')
    op.drop_index(op.f('ix_docucr_client_id'), table_name='client', schema='docucr')
    op.drop_table('client', schema='docucr')
    # ### end Alembic commands ###
