"""update_role_schema

Revision ID: 21561e3d2256
Revises: c7d088f66752
Create Date: 2026-02-05 13:56:49.706097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '21561e3d2256'
down_revision = 'c7d088f66752'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('provider', schema='docucr')
    # op.drop_table('client_location', schema='docucr')
    op.add_column('role', sa.Column('organisation_id', sa.String(), nullable=True), schema='docucr')
    op.create_foreign_key(None, 'role', 'organisation', ['organisation_id'], ['id'], source_schema='docucr', referent_schema='docucr')
    op.create_foreign_key(None, 'role', 'user', ['created_by'], ['id'], source_schema='docucr', referent_schema='docucr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', schema='docucr', type_='foreignkey')
    op.drop_constraint(None, 'role', schema='docucr', type_='foreignkey')
    op.drop_column('role', 'organisation_id', schema='docucr')
    op.create_table('client_location',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('address_line_1', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('address_line_2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('state_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('state_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('country', sa.TEXT(), server_default=sa.text("'United States'::text"), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_primary', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['docucr.client.id'], name=op.f('fk_client_location_client'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('client_location_pkey')),
    schema='docucr'
    )
    op.create_table('provider',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('middle_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('npi', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address_line_1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address_line_2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('state_code', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('state_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('country', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('location_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['docucr.client.id'], name=op.f('provider_client_id_fkey')),
    sa.ForeignKeyConstraint(['location_id'], ['docucr.client_location.id'], name=op.f('fk_location')),
    sa.PrimaryKeyConstraint('id', name=op.f('provider_pkey')),
    schema='docucr'
    )
    # ### end Alembic commands ###
