"""rename_user_id_to_created_by

Revision ID: 2a08a205fd48
Revises: 72ffad4f8930
Create Date: 2026-02-05 11:54:06.715294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '2a08a205fd48'
down_revision = '72ffad4f8930'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider', schema='docucr')
    op.drop_table('client_location', schema='docucr')
    op.add_column('user', sa.Column('created_by', sa.String(), nullable=True), schema='docucr')
    op.drop_constraint(op.f('user_user_id_fkey'), 'user', schema='docucr', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'user', ['created_by'], ['id'], source_schema='docucr', referent_schema='docucr')
    op.drop_column('user', 'user_id', schema='docucr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True), schema='docucr')
    op.drop_constraint(None, 'user', schema='docucr', type_='foreignkey')
    op.create_foreign_key(op.f('user_user_id_fkey'), 'user', 'user', ['user_id'], ['id'], source_schema='docucr', referent_schema='docucr')
    op.drop_column('user', 'created_by', schema='docucr')
    op.create_table('client_location',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('address_line_1', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('address_line_2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('state_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('state_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('country', sa.TEXT(), server_default=sa.text("'United States'::text"), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_primary', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['docucr.client.id'], name=op.f('fk_client_location_client'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('client_location_pkey')),
    schema='docucr'
    )
    op.create_table('provider',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('middle_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('npi', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address_line_1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address_line_2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('state_code', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('state_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('country', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['docucr.client.id'], name=op.f('provider_client_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('provider_pkey')),
    schema='docucr'
    )
    # ### end Alembic commands ###
