"""add_address_details_and_form_defaults

Revision ID: 363ebe23d32b
Revises: 129948718cb2
Create Date: 2026-01-29 17:55:49.104630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '363ebe23d32b'
down_revision = '129948718cb2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('address_line_1', sa.String(length=250), nullable=True), schema='docucr')
    op.add_column('client', sa.Column('address_line_2', sa.String(length=250), nullable=True), schema='docucr')
    op.add_column('client', sa.Column('state_name', sa.String(length=50), nullable=True), schema='docucr')
    op.alter_column('document_shares', 'shared_by',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='docucr')
    op.alter_column('document_shares', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='docucr')
    op.create_index('ix_document_shares_document_id', 'document_shares', ['document_id'], unique=False, schema='docucr')
    op.create_index('ix_document_shares_user_id', 'document_shares', ['user_id'], unique=False, schema='docucr')
    op.create_unique_constraint('uq_document_user_share', 'document_shares', ['document_id', 'user_id'], schema='docucr')
    op.drop_constraint(op.f('document_shares_document_id_fkey'), 'document_shares', schema='docucr', type_='foreignkey')
    op.drop_constraint(op.f('document_shares_user_id_fkey'), 'document_shares', schema='docucr', type_='foreignkey')
    op.drop_constraint(op.f('document_shares_shared_by_fkey'), 'document_shares', schema='docucr', type_='foreignkey')
    op.create_foreign_key(None, 'document_shares', 'user', ['shared_by'], ['id'], source_schema='docucr', referent_schema='docucr', ondelete='SET NULL')
    op.create_foreign_key(None, 'document_shares', 'documents', ['document_id'], ['id'], source_schema='docucr', referent_schema='docucr', ondelete='CASCADE')
    op.create_foreign_key(None, 'document_shares', 'user', ['user_id'], ['id'], source_schema='docucr', referent_schema='docucr', ondelete='CASCADE')
    op.alter_column('documents', 'enable_ai',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               schema='docucr')
    op.add_column('form_field', sa.Column('default_value', sa.JSON(), nullable=True), schema='docucr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_field', 'default_value', schema='docucr')
    op.alter_column('documents', 'enable_ai',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='docucr')
    op.drop_constraint(None, 'document_shares', schema='docucr', type_='foreignkey')
    op.drop_constraint(None, 'document_shares', schema='docucr', type_='foreignkey')
    op.drop_constraint(None, 'document_shares', schema='docucr', type_='foreignkey')
    op.create_foreign_key(op.f('document_shares_shared_by_fkey'), 'document_shares', 'user', ['shared_by'], ['id'], source_schema='docucr', referent_schema='docucr')
    op.create_foreign_key(op.f('document_shares_user_id_fkey'), 'document_shares', 'user', ['user_id'], ['id'], source_schema='docucr', referent_schema='docucr')
    op.create_foreign_key(op.f('document_shares_document_id_fkey'), 'document_shares', 'documents', ['document_id'], ['id'], source_schema='docucr', referent_schema='docucr')
    op.drop_constraint('uq_document_user_share', 'document_shares', schema='docucr', type_='unique')
    op.drop_index('ix_document_shares_user_id', table_name='document_shares', schema='docucr')
    op.drop_index('ix_document_shares_document_id', table_name='document_shares', schema='docucr')
    op.alter_column('document_shares', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='docucr')
    op.alter_column('document_shares', 'shared_by',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='docucr')
    op.drop_column('client', 'state_name', schema='docucr')
    op.drop_column('client', 'address_line_2', schema='docucr')
    op.drop_column('client', 'address_line_1', schema='docucr')
    # ### end Alembic commands ###
