"""rename_role_user_id_to_created_by

Revision ID: 4d42fc85e650
Revises: 2a08a205fd48
Create Date: 2026-02-05 12:16:22.816494

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

"""rename_role_user_id_to_created_by

Revision ID: 4d42fc85e650
Revises: 2a08a205fd48
Create Date: 2026-02-05 12:16:22.816494

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '4d42fc85e650'
down_revision = '2a08a205fd48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('client_location', schema='docucr')
    # op.drop_table('provider', schema='docucr')
    
    # Drop FK first (name might need verification, using auto-generated name here)
    # op.drop_constraint(op.f('role_user_id_fkey'), 'role', schema='docucr', type_='foreignkey')
    
    # Rename column
    op.execute('ALTER TABLE docucr.role RENAME COLUMN user_id TO created_by')
    
    # Note: No new FK created as requested
    # op.add_column('role', sa.Column('created_by', sa.String(), nullable=True), schema='docucr')
    # op.drop_column('role', 'user_id', schema='docucr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE docucr.role RENAME COLUMN created_by TO user_id')
    op.create_foreign_key(op.f('role_user_id_fkey'), 'role', 'user', ['user_id'], ['id'], source_schema='docucr', referent_schema='docucr')
    
    # op.add_column('role', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True), schema='docucr')
    # op.drop_column('role', 'created_by', schema='docucr')
    
    op.create_table('provider',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('middle_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('npi', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address_line_1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address_line_2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('state_code', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('state_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('country', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('location_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['docucr.client.id'], name=op.f('provider_client_id_fkey')),
    sa.ForeignKeyConstraint(['location_id'], ['docucr.client_location.id'], name=op.f('fk_location')),
    sa.PrimaryKeyConstraint('id', name=op.f('provider_pkey')),
    schema='docucr'
    )
    op.create_table('client_location',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('address_line_1', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('address_line_2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('state_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('state_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('country', sa.TEXT(), server_default=sa.text("'United States'::text"), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_primary', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['docucr.client.id'], name=op.f('fk_client_location_client'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('client_location_pkey')),
    schema='docucr'
    )
    # ### end Alembic commands ###
