"""initial_schema

Revision ID: 5039ad755cd9
Revises: 
Create Date: 2026-01-27 11:16:30.074444

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '5039ad755cd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='docucr')
    op.alter_column('client', 'is_user',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True,
               schema='docucr')
    op.alter_column('client', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True,
               schema='docucr')
    op.alter_column('document_form_data', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True,
               schema='docucr')
    op.alter_column('document_form_data', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True,
               schema='docucr')
    op.create_index(op.f('ix_docucr_document_form_data_id'), 'document_form_data', ['id'], unique=False, schema='docucr')
    op.create_foreign_key(None, 'document_form_data', 'documents', ['document_id'], ['id'], source_schema='docucr', referent_schema='docucr')
    op.create_foreign_key(None, 'document_form_data', 'form', ['form_id'], ['id'], source_schema='docucr', referent_schema='docucr')
    op.alter_column('document_list_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True,
               schema='docucr')
    op.create_index(op.f('ix_docucr_document_list_configs_id'), 'document_list_configs', ['id'], unique=False, schema='docucr')
    op.alter_column('document_shares', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='docucr')
    op.create_foreign_key(None, 'document_shares', 'user', ['shared_by'], ['id'], source_schema='docucr', referent_schema='docucr')
    op.create_foreign_key(None, 'document_shares', 'user', ['user_id'], ['id'], source_schema='docucr', referent_schema='docucr')
    op.create_foreign_key(None, 'document_shares', 'documents', ['document_id'], ['id'], source_schema='docucr', referent_schema='docucr')
    op.alter_column('document_types', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='docucr')
    op.alter_column('document_types', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='docucr')
    op.alter_column('documents', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='docucr')
    op.alter_column('documents', 'upload_progress',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True,
               schema='docucr')
    op.alter_column('documents', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False,
               schema='docucr')
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='docucr')
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='docucr')
    op.alter_column('documents', 'enable_ai',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True,
               schema='docucr')
    op.create_index(op.f('ix_docucr_documents_id'), 'documents', ['id'], unique=False, schema='docucr')
    op.alter_column('extracted_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True,
               schema='docucr')
    op.alter_column('extracted_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True,
               schema='docucr')
    op.create_index(op.f('ix_docucr_form_id'), 'form', ['id'], unique=False, schema='docucr')
    op.create_index(op.f('ix_docucr_form_name'), 'form', ['name'], unique=False, schema='docucr')
    op.alter_column('form_field', 'required',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True,
               schema='docucr')
    op.alter_column('form_field', 'options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('form_field', 'validation',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('form_field', 'is_system',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True,
               schema='docucr')
    op.create_index(op.f('ix_docucr_form_field_id'), 'form_field', ['id'], unique=False, schema='docucr')
    op.alter_column('role', 'can_edit',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True,
               schema='docucr')
    op.create_index(op.f('ix_docucr_status_code'), 'status', ['code'], unique=True, schema='docucr')
    op.create_index(op.f('ix_docucr_status_id'), 'status', ['id'], unique=False, schema='docucr')
    op.alter_column('templates', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='docucr')
    op.alter_column('templates', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='docucr')
    op.alter_column('templates', 'extraction_fields',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::json"),
               schema='docucr')
    op.alter_column('templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='docucr')
    op.alter_column('templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='docucr')
    op.create_foreign_key(None, 'templates', 'user', ['updated_by'], ['id'], source_schema='docucr', referent_schema='docucr')
    op.create_foreign_key(None, 'templates', 'document_types', ['document_type_id'], ['id'], source_schema='docucr', referent_schema='docucr')
    op.create_foreign_key(None, 'templates', 'user', ['created_by'], ['id'], source_schema='docucr', referent_schema='docucr')
    op.alter_column('unverified_documents', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True,
               schema='docucr')
    op.alter_column('unverified_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True,
               schema='docucr')
    op.alter_column('unverified_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True,
               schema='docucr')
    op.alter_column('user', 'is_supervisor',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True,
               schema='docucr')
    op.create_index(op.f('ix_docucr_user_client_id'), 'user_client', ['id'], unique=False, schema='docucr')
    op.create_foreign_key(None, 'user_client', 'user', ['user_id'], ['id'], source_schema='docucr', referent_schema='docucr')
    op.create_foreign_key(None, 'user_client', 'client', ['client_id'], ['id'], source_schema='docucr', referent_schema='docucr')
    op.create_index(op.f('ix_docucr_user_supervisor_id'), 'user_supervisor', ['id'], unique=False, schema='docucr')
    op.create_foreign_key(None, 'user_supervisor', 'user', ['supervisor_id'], ['id'], source_schema='docucr', referent_schema='docucr')
    op.create_foreign_key(None, 'user_supervisor', 'user', ['user_id'], ['id'], source_schema='docucr', referent_schema='docucr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_supervisor', schema='docucr', type_='foreignkey')
    op.drop_constraint(None, 'user_supervisor', schema='docucr', type_='foreignkey')
    op.drop_index(op.f('ix_docucr_user_supervisor_id'), table_name='user_supervisor', schema='docucr')
    op.drop_constraint(None, 'user_client', schema='docucr', type_='foreignkey')
    op.drop_constraint(None, 'user_client', schema='docucr', type_='foreignkey')
    op.drop_index(op.f('ix_docucr_user_client_id'), table_name='user_client', schema='docucr')
    op.alter_column('user', 'is_supervisor',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('unverified_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("(now() AT TIME ZONE 'utc'::text)"),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('unverified_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("(now() AT TIME ZONE 'utc'::text)"),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('unverified_documents', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'PENDING'::character varying"),
               existing_nullable=True,
               schema='docucr')
    op.drop_constraint(None, 'templates', schema='docucr', type_='foreignkey')
    op.drop_constraint(None, 'templates', schema='docucr', type_='foreignkey')
    op.drop_constraint(None, 'templates', schema='docucr', type_='foreignkey')
    op.alter_column('templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='docucr')
    op.alter_column('templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='docucr')
    op.alter_column('templates', 'extraction_fields',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::json"),
               schema='docucr')
    op.alter_column('templates', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='docucr')
    op.alter_column('templates', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False,
               schema='docucr')
    op.drop_index(op.f('ix_docucr_status_id'), table_name='status', schema='docucr')
    op.drop_index(op.f('ix_docucr_status_code'), table_name='status', schema='docucr')
    op.alter_column('role', 'can_edit',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True,
               schema='docucr')
    op.drop_index(op.f('ix_docucr_form_field_id'), table_name='form_field', schema='docucr')
    op.alter_column('form_field', 'is_system',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('form_field', 'validation',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('form_field', 'options',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('form_field', 'required',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True,
               schema='docucr')
    op.drop_index(op.f('ix_docucr_form_name'), table_name='form', schema='docucr')
    op.drop_index(op.f('ix_docucr_form_id'), table_name='form', schema='docucr')
    op.alter_column('extracted_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("(now() AT TIME ZONE 'utc'::text)"),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('extracted_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("(now() AT TIME ZONE 'utc'::text)"),
               existing_nullable=True,
               schema='docucr')
    op.drop_index(op.f('ix_docucr_documents_id'), table_name='documents', schema='docucr')
    op.alter_column('documents', 'enable_ai',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='docucr')
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='docucr')
    op.alter_column('documents', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False,
               schema='docucr')
    op.alter_column('documents', 'upload_progress',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('documents', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='docucr')
    op.alter_column('document_types', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='docucr')
    op.alter_column('document_types', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False,
               schema='docucr')
    op.drop_constraint(None, 'document_shares', schema='docucr', type_='foreignkey')
    op.drop_constraint(None, 'document_shares', schema='docucr', type_='foreignkey')
    op.drop_constraint(None, 'document_shares', schema='docucr', type_='foreignkey')
    op.alter_column('document_shares', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False,
               schema='docucr')
    op.drop_index(op.f('ix_docucr_document_list_configs_id'), table_name='document_list_configs', schema='docucr')
    op.alter_column('document_list_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True,
               schema='docucr')
    op.drop_constraint(None, 'document_form_data', schema='docucr', type_='foreignkey')
    op.drop_constraint(None, 'document_form_data', schema='docucr', type_='foreignkey')
    op.drop_index(op.f('ix_docucr_document_form_data_id'), table_name='document_form_data', schema='docucr')
    op.alter_column('document_form_data', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("(now() AT TIME ZONE 'utc'::text)"),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('document_form_data', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("(now() AT TIME ZONE 'utc'::text)"),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('client', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('client', 'is_user',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('client', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False,
               schema='docucr')
    # ### end Alembic commands ###
