"""relax_status_id_constraints

Revision ID: 51766ed697b6
Revises: 72ab68fde87f
Create Date: 2026-01-27 14:01:12.191061

"""
from alembic import op
import sqlalchemy as sa


revision = '51766ed697b6'
down_revision = '72ab68fde87f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sop', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='docucr')
    op.alter_column('user', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='docucr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='docucr')
    op.alter_column('sop', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='docucr')
    # ### end Alembic commands ###
