"""add_is_client_to_organisation

Revision ID: 52046e4e67a1
Revises: 9b8aaedc1409
Create Date: 2026-02-05 10:50:54.333807

"""
from alembic import op
import sqlalchemy as sa


revision = '52046e4e67a1'
down_revision = '9b8aaedc1409'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('is_client', sa.Boolean(), nullable=True), schema='docucr')
    op.add_column('organisation', sa.Column('client_id', sa.UUID(), nullable=True), schema='docucr')
    op.create_foreign_key(None, 'organisation', 'client', ['client_id'], ['id'], source_schema='docucr', referent_schema='docucr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organisation', schema='docucr', type_='foreignkey')
    op.drop_column('organisation', 'client_id', schema='docucr')
    op.drop_column('organisation', 'is_client', schema='docucr')
    # ### end Alembic commands ###
