"""sync_staging_schema_cleanup

Revision ID: 72ab68fde87f
Revises: 5039ad755cd9
Create Date: 2026-01-27 13:40:33.015815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '72ab68fde87f'
down_revision = '5039ad755cd9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    
    # Monkey-patch drop_index and drop_constraint to ignore errors using SAVEPOINT
    original_drop_index = op.drop_index
    def safe_drop_index(*args, **kwargs):
        conn = op.get_bind()
        conn.execute(sa.text("SAVEPOINT ignore_idx"))
        try:
            original_drop_index(*args, **kwargs)
            conn.execute(sa.text("RELEASE SAVEPOINT ignore_idx"))
        except sa.exc.ProgrammingError as e:
            conn.execute(sa.text("ROLLBACK TO SAVEPOINT ignore_idx"))
            print(f"Ignored missing index error: {e}")

    original_drop_constraint = op.drop_constraint
    def safe_drop_constraint(*args, **kwargs):
        conn = op.get_bind()
        conn.execute(sa.text("SAVEPOINT ignore_const"))
        try:
            original_drop_constraint(*args, **kwargs)
            conn.execute(sa.text("RELEASE SAVEPOINT ignore_const"))
        except sa.exc.ProgrammingError as e:
            conn.execute(sa.text("ROLLBACK TO SAVEPOINT ignore_const"))
            print(f"Ignored missing constraint error: {e}")

    op.drop_index = safe_drop_index
    op.drop_constraint = safe_drop_constraint

    original_create_index = op.create_index
    def safe_create_index(*args, **kwargs):
        conn = op.get_bind()
        conn.execute(sa.text("SAVEPOINT ignore_idx_create"))
        try:
            original_create_index(*args, **kwargs)
            conn.execute(sa.text("RELEASE SAVEPOINT ignore_idx_create"))
        except (sa.exc.ProgrammingError, sa.exc.DatabaseError) as e:
            conn.execute(sa.text("ROLLBACK TO SAVEPOINT ignore_idx_create"))
            print(f"Ignored index create error: {e}")
    op.create_index = safe_create_index

    original_create_foreign_key = op.create_foreign_key
    def safe_create_foreign_key(*args, **kwargs):
        conn = op.get_bind()
        conn.execute(sa.text("SAVEPOINT ignore_fk_create"))
        try:
            original_create_foreign_key(*args, **kwargs)
            conn.execute(sa.text("RELEASE SAVEPOINT ignore_fk_create"))
        except (sa.exc.ProgrammingError, sa.exc.DatabaseError) as e:
            conn.execute(sa.text("ROLLBACK TO SAVEPOINT ignore_fk_create"))
            print(f"Ignored FK create error: {e}")
    op.create_foreign_key = safe_create_foreign_key

    # Conditional add workflow_status_id
    sop_cols = [c['name'] for c in inspector.get_columns('sop', schema='docucr')]
    if 'workflow_status_id' not in sop_cols:
         op.add_column('sop', sa.Column('workflow_status_id', sa.Integer(), nullable=True), schema='docucr')
         op.create_foreign_key(None, 'sop', 'status', ['workflow_status_id'], ['id'], source_schema='docucr', referent_schema='docucr')

    # Guarded drops for is_active
    user_cols = [c['name'] for c in inspector.get_columns('user', schema='docucr')]
    role_cols = [c['name'] for c in inspector.get_columns('role', schema='docucr')]

    op.alter_column('client', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='docucr')
    op.alter_column('client', 'is_user',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True,
               schema='docucr')
    op.alter_column('client', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True,
               schema='docucr')
    op.drop_index(op.f('idx_client_user_id'), table_name='client', schema='docucr')
    op.alter_column('document_form_data', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True,
               schema='docucr')
    op.alter_column('document_form_data', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True,
               schema='docucr')
    op.create_index(op.f('ix_docucr_document_form_data_id'), 'document_form_data', ['id'], unique=False, schema='docucr')
    op.drop_constraint(op.f('document_form_data_form_id_fkey'), 'document_form_data', schema='docucr', type_='foreignkey')
    op.drop_constraint(op.f('document_form_data_document_id_fkey'), 'document_form_data', schema='docucr', type_='foreignkey')
    op.create_foreign_key(None, 'document_form_data', 'form', ['form_id'], ['id'], source_schema='docucr', referent_schema='docucr')
    op.create_foreign_key(None, 'document_form_data', 'documents', ['document_id'], ['id'], source_schema='docucr', referent_schema='docucr')
    op.alter_column('document_list_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True,
               schema='docucr')
    op.create_index(op.f('ix_docucr_document_list_configs_id'), 'document_list_configs', ['id'], unique=False, schema='docucr')
    op.alter_column('document_shares', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='docucr')
    op.drop_constraint(op.f('document_shares_document_id_user_id_key'), 'document_shares', schema='docucr', type_='unique')
    op.drop_index(op.f('idx_document_shares_document_id'), table_name='document_shares', schema='docucr')
    op.drop_index(op.f('idx_document_shares_shared_by'), table_name='document_shares', schema='docucr')
    op.drop_index(op.f('idx_document_shares_user_id'), table_name='document_shares', schema='docucr')
    op.drop_constraint(op.f('document_shares_user_id_fkey'), 'document_shares', schema='docucr', type_='foreignkey')
    op.drop_constraint(op.f('document_shares_shared_by_fkey'), 'document_shares', schema='docucr', type_='foreignkey')
    op.drop_constraint(op.f('document_shares_document_id_fkey'), 'document_shares', schema='docucr', type_='foreignkey')
    op.create_foreign_key(None, 'document_shares', 'user', ['user_id'], ['id'], source_schema='docucr', referent_schema='docucr')
    op.create_foreign_key(None, 'document_shares', 'documents', ['document_id'], ['id'], source_schema='docucr', referent_schema='docucr')
    op.create_foreign_key(None, 'document_shares', 'user', ['shared_by'], ['id'], source_schema='docucr', referent_schema='docucr')
    op.alter_column('document_types', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='docucr')
    op.alter_column('document_types', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='docucr')
    op.drop_index(op.f('idx_document_types_name'), table_name='document_types', schema='docucr')
    op.alter_column('documents', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='docucr')
    op.alter_column('documents', 'upload_progress',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True,
               schema='docucr')
    op.alter_column('documents', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False,
               schema='docucr')
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='docucr')
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='docucr')
    op.alter_column('documents', 'enable_ai',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True,
               schema='docucr')
    op.drop_index(op.f('idx_documents_is_archived'), table_name='documents', schema='docucr')
    op.drop_index(op.f('idx_documents_user_id'), table_name='documents', schema='docucr')
    op.create_index(op.f('ix_docucr_documents_id'), 'documents', ['id'], unique=False, schema='docucr')
    op.alter_column('extracted_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True,
               schema='docucr')
    op.alter_column('extracted_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True,
               schema='docucr')
    op.drop_index(op.f('idx_form_name'), table_name='form', schema='docucr')
    op.create_index(op.f('ix_docucr_form_id'), 'form', ['id'], unique=False, schema='docucr')
    op.create_index(op.f('ix_docucr_form_name'), 'form', ['name'], unique=False, schema='docucr')
    op.alter_column('form_field', 'required',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True,
               schema='docucr')
    op.alter_column('form_field', 'options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('form_field', 'validation',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('form_field', 'is_system',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True,
               schema='docucr')
    op.drop_index(op.f('idx_form_field_form_id'), table_name='form_field', schema='docucr')
    op.drop_index(op.f('idx_form_field_order'), table_name='form_field', schema='docucr')
    op.create_index(op.f('ix_docucr_form_field_id'), 'form_field', ['id'], unique=False, schema='docucr')
    op.alter_column('role', 'can_edit',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True,
               schema='docucr')
    if 'is_active' in role_cols:
        op.drop_column('role', 'is_active', schema='docucr')
    op.drop_index(op.f('idx_sop_status_id'), table_name='sop', schema='docucr')
    # op.drop_index(op.f('idx_sop_workflow_status_id'), table_name='sop', schema='docucr')
    op.drop_constraint(op.f('status_new_code_key'), 'status', schema='docucr', type_='unique')
    op.create_index(op.f('ix_docucr_status_code'), 'status', ['code'], unique=True, schema='docucr')
    op.create_index(op.f('ix_docucr_status_id'), 'status', ['id'], unique=False, schema='docucr')
    op.alter_column('templates', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='docucr')
    op.alter_column('templates', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='docucr')
    op.alter_column('templates', 'extraction_fields',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::json"),
               schema='docucr')
    op.alter_column('templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='docucr')
    op.alter_column('templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='docucr')
    op.drop_index(op.f('idx_templates_document_type_id'), table_name='templates', schema='docucr')
    op.drop_index(op.f('idx_templates_name'), table_name='templates', schema='docucr')
    op.drop_constraint(op.f('templates_document_type_id_fkey'), 'templates', schema='docucr', type_='foreignkey')
    op.drop_constraint(op.f('fk_templates_created_by'), 'templates', schema='docucr', type_='foreignkey')
    op.drop_constraint(op.f('fk_templates_updated_by'), 'templates', schema='docucr', type_='foreignkey')
    op.create_foreign_key(None, 'templates', 'document_types', ['document_type_id'], ['id'], source_schema='docucr', referent_schema='docucr')
    op.create_foreign_key(None, 'templates', 'user', ['updated_by'], ['id'], source_schema='docucr', referent_schema='docucr')
    op.create_foreign_key(None, 'templates', 'user', ['created_by'], ['id'], source_schema='docucr', referent_schema='docucr')
    op.alter_column('unverified_documents', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True,
               schema='docucr')
    op.alter_column('unverified_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True,
               schema='docucr')
    op.alter_column('unverified_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True,
               schema='docucr')
    op.alter_column('user', 'is_supervisor',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True,
               schema='docucr')
    op.drop_index(op.f('idx_user_client_id'), table_name='user', schema='docucr')
    if 'is_active' in user_cols:
        op.drop_column('user', 'is_active', schema='docucr')
    op.drop_index(op.f('ix_docucr_user_client_client_id'), table_name='user_client', schema='docucr')
    op.drop_index(op.f('ix_docucr_user_client_user_id'), table_name='user_client', schema='docucr')
    op.drop_constraint(op.f('user_client_user_id_client_id_key'), 'user_client', schema='docucr', type_='unique')
    op.create_index(op.f('ix_docucr_user_client_id'), 'user_client', ['id'], unique=False, schema='docucr')
    op.drop_constraint(op.f('user_client_client_id_fkey'), 'user_client', schema='docucr', type_='foreignkey')
    op.drop_constraint(op.f('user_client_user_id_fkey'), 'user_client', schema='docucr', type_='foreignkey')
    op.create_foreign_key(None, 'user_client', 'user', ['user_id'], ['id'], source_schema='docucr', referent_schema='docucr')
    op.create_foreign_key(None, 'user_client', 'client', ['client_id'], ['id'], source_schema='docucr', referent_schema='docucr')
    op.drop_index(op.f('idx_user_supervisor_supervisor_id'), table_name='user_supervisor', schema='docucr')
    op.drop_index(op.f('idx_user_supervisor_user_id'), table_name='user_supervisor', schema='docucr')
    op.drop_constraint(op.f('unique_user_supervisor'), 'user_supervisor', schema='docucr', type_='unique')
    op.create_index(op.f('ix_docucr_user_supervisor_id'), 'user_supervisor', ['id'], unique=False, schema='docucr')
    op.drop_constraint(op.f('user_supervisor_supervisor_id_fkey'), 'user_supervisor', schema='docucr', type_='foreignkey')
    op.drop_constraint(op.f('user_supervisor_user_id_fkey'), 'user_supervisor', schema='docucr', type_='foreignkey')
    op.create_foreign_key(None, 'user_supervisor', 'user', ['user_id'], ['id'], source_schema='docucr', referent_schema='docucr')
    op.create_foreign_key(None, 'user_supervisor', 'user', ['supervisor_id'], ['id'], source_schema='docucr', referent_schema='docucr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_supervisor', schema='docucr', type_='foreignkey')
    op.drop_constraint(None, 'user_supervisor', schema='docucr', type_='foreignkey')
    op.create_foreign_key(op.f('user_supervisor_user_id_fkey'), 'user_supervisor', 'user', ['user_id'], ['id'], source_schema='docucr', referent_schema='docucr', ondelete='CASCADE')
    op.create_foreign_key(op.f('user_supervisor_supervisor_id_fkey'), 'user_supervisor', 'user', ['supervisor_id'], ['id'], source_schema='docucr', referent_schema='docucr', ondelete='CASCADE')
    op.drop_index(op.f('ix_docucr_user_supervisor_id'), table_name='user_supervisor', schema='docucr')
    op.create_unique_constraint(op.f('unique_user_supervisor'), 'user_supervisor', ['user_id'], schema='docucr', postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_user_supervisor_user_id'), 'user_supervisor', ['user_id'], unique=False, schema='docucr')
    op.create_index(op.f('idx_user_supervisor_supervisor_id'), 'user_supervisor', ['supervisor_id'], unique=False, schema='docucr')
    op.drop_constraint(None, 'user_client', schema='docucr', type_='foreignkey')
    op.drop_constraint(None, 'user_client', schema='docucr', type_='foreignkey')
    op.create_foreign_key(op.f('user_client_user_id_fkey'), 'user_client', 'user', ['user_id'], ['id'], source_schema='docucr', referent_schema='docucr', ondelete='CASCADE')
    op.create_foreign_key(op.f('user_client_client_id_fkey'), 'user_client', 'client', ['client_id'], ['id'], source_schema='docucr', referent_schema='docucr', ondelete='CASCADE')
    op.drop_index(op.f('ix_docucr_user_client_id'), table_name='user_client', schema='docucr')
    op.create_unique_constraint(op.f('user_client_user_id_client_id_key'), 'user_client', ['user_id', 'client_id'], schema='docucr', postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_docucr_user_client_user_id'), 'user_client', ['user_id'], unique=False, schema='docucr')
    op.create_index(op.f('ix_docucr_user_client_client_id'), 'user_client', ['client_id'], unique=False, schema='docucr')
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True), schema='docucr')
    op.create_index(op.f('idx_user_client_id'), 'user', ['client_id'], unique=False, schema='docucr')
    op.alter_column('user', 'is_supervisor',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('unverified_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("(now() AT TIME ZONE 'utc'::text)"),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('unverified_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("(now() AT TIME ZONE 'utc'::text)"),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('unverified_documents', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'PENDING'::character varying"),
               existing_nullable=True,
               schema='docucr')
    op.drop_constraint(None, 'templates', schema='docucr', type_='foreignkey')
    op.drop_constraint(None, 'templates', schema='docucr', type_='foreignkey')
    op.drop_constraint(None, 'templates', schema='docucr', type_='foreignkey')
    op.create_foreign_key(op.f('fk_templates_updated_by'), 'templates', 'user', ['updated_by'], ['id'], source_schema='docucr', referent_schema='docucr', ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_templates_created_by'), 'templates', 'user', ['created_by'], ['id'], source_schema='docucr', referent_schema='docucr', ondelete='RESTRICT')
    op.create_foreign_key(op.f('templates_document_type_id_fkey'), 'templates', 'document_types', ['document_type_id'], ['id'], source_schema='docucr', referent_schema='docucr', ondelete='CASCADE')
    op.create_index(op.f('idx_templates_name'), 'templates', ['template_name'], unique=False, schema='docucr')
    op.create_index(op.f('idx_templates_document_type_id'), 'templates', ['document_type_id'], unique=False, schema='docucr')
    op.alter_column('templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='docucr')
    op.alter_column('templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='docucr')
    op.alter_column('templates', 'extraction_fields',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::json"),
               schema='docucr')
    op.alter_column('templates', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='docucr')
    op.alter_column('templates', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False,
               schema='docucr')
    op.drop_index(op.f('ix_docucr_status_id'), table_name='status', schema='docucr')
    op.drop_index(op.f('ix_docucr_status_code'), table_name='status', schema='docucr')
    op.create_unique_constraint(op.f('status_new_code_key'), 'status', ['code'], schema='docucr', postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_sop_workflow_status_id'), 'sop', ['workflow_status_id'], unique=False, schema='docucr')
    op.create_index(op.f('idx_sop_status_id'), 'sop', ['status_id'], unique=False, schema='docucr')
    op.add_column('role', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True), schema='docucr')
    op.alter_column('role', 'can_edit',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True,
               schema='docucr')
    op.drop_index(op.f('ix_docucr_form_field_id'), table_name='form_field', schema='docucr')
    op.create_index(op.f('idx_form_field_order'), 'form_field', ['form_id', 'order'], unique=False, schema='docucr')
    op.create_index(op.f('idx_form_field_form_id'), 'form_field', ['form_id'], unique=False, schema='docucr')
    op.alter_column('form_field', 'is_system',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('form_field', 'validation',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('form_field', 'options',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('form_field', 'required',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True,
               schema='docucr')
    op.drop_index(op.f('ix_docucr_form_name'), table_name='form', schema='docucr')
    op.drop_index(op.f('ix_docucr_form_id'), table_name='form', schema='docucr')
    op.create_index(op.f('idx_form_name'), 'form', ['name'], unique=False, schema='docucr')
    op.alter_column('extracted_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("(now() AT TIME ZONE 'utc'::text)"),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('extracted_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("(now() AT TIME ZONE 'utc'::text)"),
               existing_nullable=True,
               schema='docucr')
    op.drop_index(op.f('ix_docucr_documents_id'), table_name='documents', schema='docucr')
    op.create_index(op.f('idx_documents_user_id'), 'documents', ['user_id'], unique=False, schema='docucr')
    op.create_index(op.f('idx_documents_is_archived'), 'documents', ['is_archived'], unique=False, schema='docucr')
    op.alter_column('documents', 'enable_ai',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='docucr')
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='docucr')
    op.alter_column('documents', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False,
               schema='docucr')
    op.alter_column('documents', 'upload_progress',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('documents', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='docucr')
    op.create_index(op.f('idx_document_types_name'), 'document_types', ['name'], unique=False, schema='docucr')
    op.alter_column('document_types', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='docucr')
    op.alter_column('document_types', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False,
               schema='docucr')
    op.drop_constraint(None, 'document_shares', schema='docucr', type_='foreignkey')
    op.drop_constraint(None, 'document_shares', schema='docucr', type_='foreignkey')
    op.drop_constraint(None, 'document_shares', schema='docucr', type_='foreignkey')
    op.create_foreign_key(op.f('document_shares_document_id_fkey'), 'document_shares', 'documents', ['document_id'], ['id'], source_schema='docucr', referent_schema='docucr', ondelete='CASCADE')
    op.create_foreign_key(op.f('document_shares_shared_by_fkey'), 'document_shares', 'user', ['shared_by'], ['id'], source_schema='docucr', referent_schema='docucr', ondelete='CASCADE')
    op.create_foreign_key(op.f('document_shares_user_id_fkey'), 'document_shares', 'user', ['user_id'], ['id'], source_schema='docucr', referent_schema='docucr', ondelete='CASCADE')
    op.create_index(op.f('idx_document_shares_user_id'), 'document_shares', ['user_id'], unique=False, schema='docucr')
    op.create_index(op.f('idx_document_shares_shared_by'), 'document_shares', ['shared_by'], unique=False, schema='docucr')
    op.create_index(op.f('idx_document_shares_document_id'), 'document_shares', ['document_id'], unique=False, schema='docucr')
    op.create_unique_constraint(op.f('document_shares_document_id_user_id_key'), 'document_shares', ['document_id', 'user_id'], schema='docucr', postgresql_nulls_not_distinct=False)
    op.alter_column('document_shares', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False,
               schema='docucr')
    op.drop_index(op.f('ix_docucr_document_list_configs_id'), table_name='document_list_configs', schema='docucr')
    op.alter_column('document_list_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True,
               schema='docucr')
    op.drop_constraint(None, 'document_form_data', schema='docucr', type_='foreignkey')
    op.drop_constraint(None, 'document_form_data', schema='docucr', type_='foreignkey')
    op.create_foreign_key(op.f('document_form_data_document_id_fkey'), 'document_form_data', 'documents', ['document_id'], ['id'], source_schema='docucr', referent_schema='docucr', ondelete='CASCADE')
    op.create_foreign_key(op.f('document_form_data_form_id_fkey'), 'document_form_data', 'form', ['form_id'], ['id'], source_schema='docucr', referent_schema='docucr', ondelete='SET NULL')
    op.drop_index(op.f('ix_docucr_document_form_data_id'), table_name='document_form_data', schema='docucr')
    op.alter_column('document_form_data', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("(now() AT TIME ZONE 'utc'::text)"),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('document_form_data', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("(now() AT TIME ZONE 'utc'::text)"),
               existing_nullable=True,
               schema='docucr')
    op.create_index(op.f('idx_client_user_id'), 'client', ['user_id'], unique=False, schema='docucr')
    op.alter_column('client', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('client', 'is_user',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('client', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False,
               schema='docucr')
    # ### end Alembic commands ###
