"""add sop_document table

Revision ID: 7a4e615e0dd1
Revises: 72ab68fde87f
Create Date: 2026-03-05 18:21:04.460657

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '7a4e615e0dd1'
down_revision = '72ab68fde87f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sop_document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sop_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('s3_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sop_id'], ['docucr.sop.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='docucr'
    )

    # Data Migration: Move s3_key from sop to sop_document
    connection = op.get_bind()
    
    # Cleanup NULLs in other tables that were autogenerated as NOT NULL
    connection.execute(sa.text("DELETE FROM docucr.user_role WHERE user_id IS NULL"))
    connection.execute(sa.text("UPDATE docucr.document_types SET name = 'Unnamed Type' WHERE name IS NULL"))

    # Use raw SQL to avoid model dependency issues during migration
    sops = connection.execute(sa.text("SELECT id, s3_key, title FROM docucr.sop WHERE s3_key IS NOT NULL")).fetchall()
    
    import uuid
    for sop_id, s3_key, title in sops:
        connection.execute(
            sa.text("INSERT INTO docucr.sop_document (id, sop_id, name, category, s3_key) VALUES (:id, :sop_id, :name, :category, :s3_key)"),
            {
                "id": str(uuid.uuid4()),
                "sop_id": sop_id,
                "name": title if title else "Source File",
                "category": "Source file",
                "s3_key": s3_key
            }
        )

    op.drop_table('provider_client_mapping', schema='docucr')
    op.drop_constraint(op.f('document_list_configs_user_id_key'), 'document_list_configs', schema='docucr', type_='unique')
    op.alter_column('document_types', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               schema='docucr')
    # Fix NULL values in documents table before SET NOT NULL
    connection.execute(sa.text("UPDATE docucr.documents SET organisation_id = 'fe425c81-af25-4ca7-af71-5ec29756ca72' WHERE organisation_id IS NULL"))
    connection.execute(sa.text("UPDATE docucr.documents SET created_by = '2d87d712-a73f-44de-9743-e1a2e938ff49' WHERE created_by IS NULL"))

    op.alter_column('documents', 'organisation_id',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='docucr')
    op.alter_column('documents', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='docucr')
    op.drop_index(op.f('ix_docucr_organisation_id'), table_name='organisation', schema='docucr')
    op.drop_column('organisation', 'updated_at', schema='docucr')
    op.alter_column('otp', 'purpose',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False,
               schema='docucr')
    op.drop_column('sop', 's3_key', schema='docucr')
    op.alter_column('user_role', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='docucr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_role', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='docucr')
    op.add_column('sop', sa.Column('s3_key', sa.VARCHAR(), autoincrement=False, nullable=True), schema='docucr')
    op.alter_column('otp', 'purpose',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'RESET'::character varying"),
               existing_nullable=False,
               schema='docucr')
    op.add_column('organisation', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True), schema='docucr')
    op.create_index(op.f('ix_docucr_organisation_id'), 'organisation', ['id'], unique=False, schema='docucr')
    op.alter_column('documents', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='docucr')
    op.alter_column('documents', 'organisation_id',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='docucr')
    op.alter_column('document_types', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               schema='docucr')
    op.create_unique_constraint(op.f('document_list_configs_user_id_key'), 'document_list_configs', ['user_id'], schema='docucr', postgresql_nulls_not_distinct=False)
    op.create_table('provider_client_mapping',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('location_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['docucr.client.id'], name=op.f('provider_client_mapping_client_id_fkey')),
    sa.ForeignKeyConstraint(['location_id'], ['docucr.client_location.id'], name=op.f('provider_client_mapping_location_id_fkey')),
    sa.ForeignKeyConstraint(['provider_id'], ['docucr.provider.id'], name=op.f('provider_client_mapping_provider_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('provider_client_mapping_pkey')),
    schema='docucr'
    )
    op.drop_table('sop_document', schema='docucr')
    # ### end Alembic commands ###
