"""add_sop_provider_mapping

Revision ID: 7ffa90fe3bbe
Revises: bec04446b9c9
Create Date: 2026-02-07 18:15:46.076857

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '7ffa90fe3bbe'
down_revision = 'bec04446b9c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sop_provider_mapping',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sop_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['docucr.provider.id'], ),
    sa.ForeignKeyConstraint(['sop_id'], ['docucr.sop.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='docucr'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sop_provider_mapping', schema='docucr')
    # ### end Alembic commands ###
