"""add_organisation_id_to_user

Revision ID: 99dceb02253b
Revises: 4d42fc85e650
Create Date: 2026-02-05 13:26:49.126938

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '99dceb02253b'
down_revision = '4d42fc85e650'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('client_location', schema='docucr')
    # op.drop_table('provider', schema='docucr')
    op.add_column('user', sa.Column('organisation_id', sa.String(), nullable=True), schema='docucr')
    op.create_foreign_key(None, 'user', 'organisation', ['organisation_id'], ['id'], source_schema='docucr', referent_schema='docucr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', schema='docucr', type_='foreignkey')
    op.drop_column('user', 'organisation_id', schema='docucr')
    # op.create_table('provider',
    # sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    # ... (truncated for brevity, actually I will just comment out the whole block or replace with nothing relevant)
    pass
    # ### end Alembic commands ###
