"""add_is_superuser_to_organisation

Revision ID: 9b8aaedc1409
Revises: 1bb1b7add63a
Create Date: 2026-02-05 10:39:04.892248

"""
from alembic import op
import sqlalchemy as sa


revision = '9b8aaedc1409'
down_revision = '1bb1b7add63a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('is_superuser', sa.Boolean(), nullable=True), schema='docucr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisation', 'is_superuser', schema='docucr')
    # ### end Alembic commands ###
