"""Add name column to organisation

Revision ID: bec04446b9c9
Revises: c08b1280c925
Create Date: 2026-02-06 15:54:56.422452

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'bec04446b9c9'
down_revision = 'c08b1280c925'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add column as nullable
    op.add_column('organisation', sa.Column('name', sa.String(), nullable=True), schema='docucr')
    
    # 2. Populate existing data
    op.execute("UPDATE docucr.organisation SET name = first_name || ' ' || last_name")
    
    # 3. Make non-nullable
    op.alter_column('organisation', 'name', nullable=False, schema='docucr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisation', 'name', schema='docucr')
    # ### end Alembic commands ###
