"""restore_created_by_fk_to_user

Revision ID: c7d088f66752
Revises: 064010508069
Create Date: 2026-02-05 13:36:59.164566

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'c7d088f66752'
down_revision = '064010508069'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('client_location', schema='docucr')
    # op.drop_table('provider', schema='docucr')
    op.create_foreign_key(None, 'user', 'user', ['created_by'], ['id'], source_schema='docucr', referent_schema='docucr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', schema='docucr', type_='foreignkey')
    pass
    # ### end Alembic commands ###
