"""create_organisation_table

Revision ID: e24b3143f299
Revises: 363ebe23d32b
Create Date: 2026-02-04 23:01:25.881166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'e24b3143f299'
down_revision = '363ebe23d32b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisation',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('phone_country_code', sa.String(length=5), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['docucr.status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='docucr'
    )
    op.create_index(op.f('ix_docucr_organisation_email'), 'organisation', ['email'], unique=True, schema='docucr')
    op.create_index(op.f('ix_docucr_organisation_id'), 'organisation', ['id'], unique=False, schema='docucr')
    op.create_index(op.f('ix_docucr_organisation_username'), 'organisation', ['username'], unique=True, schema='docucr')
    op.drop_table('provider', schema='docucr')
    op.drop_index(op.f('one_primary_location_per_client'), table_name='client_location', schema='docucr', postgresql_where='(is_primary = true)')
    op.drop_table('client_location', schema='docucr')
    op.drop_index(op.f('ix_organisations_email'), table_name='organisations', schema='docucr')
    op.drop_index(op.f('ix_organisations_id'), table_name='organisations', schema='docucr')
    op.drop_index(op.f('ix_organisations_username'), table_name='organisations', schema='docucr')
    op.drop_table('organisations', schema='docucr')
    op.create_foreign_key(None, 'user', 'user', ['user_id'], ['id'], source_schema='docucr', referent_schema='docucr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', schema='docucr', type_='foreignkey')
    op.create_table('organisations',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('middle_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone_country_code', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['docucr.status.id'], name=op.f('fk_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('organisations_pkey')),
    sa.UniqueConstraint('email', name=op.f('organisations_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name=op.f('organisations_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='docucr'
    )
    op.create_index(op.f('ix_organisations_username'), 'organisations', ['username'], unique=False, schema='docucr')
    op.create_index(op.f('ix_organisations_id'), 'organisations', ['id'], unique=False, schema='docucr')
    op.create_index(op.f('ix_organisations_email'), 'organisations', ['email'], unique=False, schema='docucr')
    op.create_table('client_location',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('address_line_1', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address_line_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('state_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('state_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['docucr.client.id'], name=op.f('client_location_client_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('client_location_pkey')),
    schema='docucr'
    )
    op.create_index(op.f('one_primary_location_per_client'), 'client_location', ['client_id'], unique=True, schema='docucr', postgresql_where='(is_primary = true)')
    op.create_table('provider',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('middle_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('npi', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_line_1', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('address_line_2', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('state_code', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('state_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint("zip_code::text ~ '^[0-9]{5}-[0-9]{4}$'::text", name=op.f('ck_client_zip_9_digit')),
    sa.CheckConstraint('char_length(state_code::text) = 2', name=op.f('ck_client_state_code_len')),
    sa.ForeignKeyConstraint(['client_id'], ['docucr.client.id'], name=op.f('provider_client_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('provider_pkey')),
    schema='docucr'
    )
    op.drop_index(op.f('ix_docucr_organisation_username'), table_name='organisation', schema='docucr')
    op.drop_index(op.f('ix_docucr_organisation_id'), table_name='organisation', schema='docucr')
    op.drop_index(op.f('ix_docucr_organisation_email'), table_name='organisation', schema='docucr')
    op.drop_table('organisation', schema='docucr')
    # ### end Alembic commands ###
