"""restore provider_client_mapping table

Revision ID: eeb406073ab4
Revises: 7a4e615e0dd1
Create Date: 2026-03-05 18:34:10.509259

"""
from alembic import op
import sqlalchemy as sa


revision = 'eeb406073ab4'
down_revision = '7a4e615e0dd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_client_mapping',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['docucr.client.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['docucr.client_location.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['docucr.provider.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='docucr'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_client_mapping', schema='docucr')
    # ### end Alembic commands ###
