"""add xyz column

Revision ID: fc25e7c3fd57
Revises: ed9b3c78c529
Create Date: 2026-02-12 15:14:36.049463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'fc25e7c3fd57'
down_revision = 'ed9b3c78c529'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_docucr_activity_log_action'), table_name='activity_log', schema='docucr')
    op.drop_index(op.f('ix_docucr_activity_log_created_at'), table_name='activity_log', schema='docucr')
    op.drop_index(op.f('ix_docucr_activity_log_entity_type'), table_name='activity_log', schema='docucr')
    op.alter_column('client_location', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='docucr')
    op.alter_column('client_location', 'address_line_1',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               schema='docucr')
    op.alter_column('client_location', 'address_line_2',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('client_location', 'city',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               schema='docucr')
    op.alter_column('client_location', 'state_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               schema='docucr')
    op.alter_column('client_location', 'state_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('client_location', 'country',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('client_location', 'zip_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               schema='docucr')
    op.alter_column('client_location', 'is_primary',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True,
               schema='docucr')
    op.drop_constraint(op.f('fk_client_location_client'), 'client_location', schema='docucr', type_='foreignkey')
    op.create_foreign_key(None, 'client_location', 'client', ['client_id'], ['id'], source_schema='docucr', referent_schema='docucr')
    op.drop_column('client_location', 'created_at', schema='docucr')
    op.alter_column('documents', 'organisation_id',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='docucr')
    op.alter_column('documents', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='docucr')
    op.create_foreign_key(None, 'documents', 'user', ['created_by'], ['id'], source_schema='docucr', referent_schema='docucr')
    op.drop_column('documents', 'organisation_name', schema='docucr')
    op.alter_column('provider', 'first_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               schema='docucr')
    op.alter_column('provider', 'middle_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('provider', 'last_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('provider', 'npi',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('provider', 'address_line_1',
               existing_type=sa.TEXT(),
               type_=sa.String(length=250),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('provider', 'address_line_2',
               existing_type=sa.TEXT(),
               type_=sa.String(length=250),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('provider', 'city',
               existing_type=sa.TEXT(),
               type_=sa.String(length=250),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('provider', 'state_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('provider', 'country',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               schema='docucr')
    op.create_index(op.f('ix_docucr_provider_npi'), 'provider', ['npi'], unique=True, schema='docucr')
    op.drop_constraint(op.f('provider_client_id_fkey'), 'provider', schema='docucr', type_='foreignkey')
    op.drop_column('provider', 'client_id', schema='docucr')
    op.drop_index(op.f('ux_role_name_org'), table_name='role', schema='docucr')
    op.create_unique_constraint('ux_role_name_org', 'role', ['name', 'organisation_id'], schema='docucr')
    op.create_index(op.f('ix_docucr_role_name'), 'role', ['name'], unique=False, schema='docucr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_docucr_role_name'), table_name='role', schema='docucr')
    op.drop_constraint('ux_role_name_org', 'role', schema='docucr', type_='unique')
    op.create_index(op.f('ux_role_name_org'), 'role', [sa.literal_column('upper(name::text)'), 'organisation_id'], unique=True, schema='docucr')
    op.add_column('provider', sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=True), schema='docucr')
    op.create_foreign_key(op.f('provider_client_id_fkey'), 'provider', 'client', ['client_id'], ['id'], source_schema='docucr', referent_schema='docucr')
    op.drop_index(op.f('ix_docucr_provider_npi'), table_name='provider', schema='docucr')
    op.alter_column('provider', 'country',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('provider', 'state_name',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('provider', 'city',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('provider', 'address_line_2',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('provider', 'address_line_1',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('provider', 'npi',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('provider', 'last_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('provider', 'middle_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('provider', 'first_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               schema='docucr')
    op.add_column('documents', sa.Column('organisation_name', sa.VARCHAR(), autoincrement=False, nullable=True), schema='docucr')
    op.drop_constraint(None, 'documents', schema='docucr', type_='foreignkey')
    op.alter_column('documents', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='docucr')
    op.alter_column('documents', 'organisation_id',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='docucr')
    op.add_column('client_location', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True), schema='docucr')
    op.drop_constraint(None, 'client_location', schema='docucr', type_='foreignkey')
    op.create_foreign_key(op.f('fk_client_location_client'), 'client_location', 'client', ['client_id'], ['id'], source_schema='docucr', referent_schema='docucr', ondelete='CASCADE')
    op.alter_column('client_location', 'is_primary',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('client_location', 'zip_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               schema='docucr')
    op.alter_column('client_location', 'country',
               existing_type=sa.String(),
               server_default=sa.text("'United States'::text"),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('client_location', 'state_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('client_location', 'state_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               schema='docucr')
    op.alter_column('client_location', 'city',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               schema='docucr')
    op.alter_column('client_location', 'address_line_2',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='docucr')
    op.alter_column('client_location', 'address_line_1',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               schema='docucr')
    op.alter_column('client_location', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False,
               schema='docucr')
    op.create_index(op.f('ix_docucr_activity_log_entity_type'), 'activity_log', ['entity_type'], unique=False, schema='docucr')
    op.create_index(op.f('ix_docucr_activity_log_created_at'), 'activity_log', ['created_at'], unique=False, schema='docucr')
    op.create_index(op.f('ix_docucr_activity_log_action'), 'activity_log', ['action'], unique=False, schema='docucr')
    op.create_table('provider_client_mapping',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('location_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['docucr.client.id'], name=op.f('provider_client_mapping_client_id_fkey')),
    sa.ForeignKeyConstraint(['location_id'], ['docucr.client_location.id'], name=op.f('provider_client_mapping_location_id_fkey')),
    sa.ForeignKeyConstraint(['provider_id'], ['docucr.provider.id'], name=op.f('provider_client_mapping_provider_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('provider_client_mapping_pkey')),
    schema='docucr'
    )
    # ### end Alembic commands ###
